![texto alternativo](https://i.imgur.com/21Ln3BP.png)

In [0]:
import torch

In [0]:
A = torch.randn((8,3,5))

In [0]:
A.size()

torch.Size([8, 3, 5])

In [0]:
A.size() == (8,3,5)

True

In [0]:
A[0][0][0]
A[0,:,0]

tensor([ 0.9886,  0.1165, -0.4597])

In [0]:
A[0,0,:]
A[0,:,0]

tensor([ 0.9886,  0.1165, -0.4597])

In [0]:
C = torch.zeros((5,5))

In [0]:
C.dtype

torch.float32

In [0]:
D = torch.randint(2,(5,5))

In [0]:
D

tensor([[1, 0, 1, 1, 1],
        [0, 1, 1, 0, 1],
        [0, 1, 0, 1, 0],
        [1, 0, 1, 0, 0],
        [0, 0, 0, 0, 0]])

In [0]:
D.dtype

torch.int64

In [0]:
C + D

RuntimeError: ignored

In [0]:
C + D.float()

tensor([[1., 0., 1., 1., 1.],
        [0., 1., 1., 0., 1.],
        [0., 1., 0., 1., 0.],
        [1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [0]:
torch.set_default_tensor_type('torch.FloatTensor')

In [0]:
C.device

device(type='cpu')

In [0]:
torch.cuda.is_available()

False

In [0]:
import torch
torch.cuda.is_available()

True

In [0]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [0]:
x = torch.randn(3,5) #cpu
y = torch.ones_like(x, device=device) #gpu

In [0]:
x = x.to(device) #gpu

In [0]:
z = x + y

In [0]:
print(z)
print(z.cpu())

tensor([[ 1.5104,  0.7930,  0.7715,  0.6314,  0.9431],
        [-0.1072,  3.0696,  1.3844,  0.4896,  0.1998],
        [ 0.2498,  2.6039, -0.3756, -1.3485,  0.9387]], device='cuda:0')
tensor([[ 1.5104,  0.7930,  0.7715,  0.6314,  0.9431],
        [-0.1072,  3.0696,  1.3844,  0.4896,  0.1998],
        [ 0.2498,  2.6039, -0.3756, -1.3485,  0.9387]])


In [0]:
from google.colab import drive
drive.mount('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /gdrive


In [0]:
from torchvision import datasets

In [0]:
dir(datasets)

['CIFAR10',
 'CIFAR100',
 'Caltech101',
 'Caltech256',
 'CelebA',
 'Cityscapes',
 'CocoCaptions',
 'CocoDetection',
 'DatasetFolder',
 'EMNIST',
 'FakeData',
 'FashionMNIST',
 'Flickr30k',
 'Flickr8k',
 'ImageFolder',
 'ImageNet',
 'KMNIST',
 'LSUN',
 'LSUNClass',
 'MNIST',
 'Omniglot',
 'PhotoTour',
 'SBDataset',
 'SBU',
 'SEMEION',
 'STL10',
 'SVHN',
 'VOCDetection',
 'VOCSegmentation',
 'VisionDataset',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'caltech',
 'celeba',
 'cifar',
 'cityscapes',
 'coco',
 'fakedata',
 'flickr',
 'folder',
 'imagenet',
 'lsun',
 'mnist',
 'omniglot',
 'phototour',
 'sbd',
 'sbu',
 'semeion',
 'stl10',
 'svhn',
 'utils',
 'vision',
 'voc']

In [0]:
cifar = datasets.CIFAR10('/gdrive/My Drive/dl-pytorch/datasets', download=True)

Files already downloaded and verified


In [0]:
len(cifar)

50000

In [0]:
data = torch.Tensor(cifar.data)

In [0]:
data.size()

torch.Size([50000, 32, 32, 3])